name: Build Firmware

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install ARM GCC
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Build firmware
      run: |
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware.bin
